# Generated by Django 2.2.3 on 2019-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_man_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='man_images',
            name='price',
            field=models.CharField(default='', max_length=20),
        ),
    ]
