# Generated by Django 2.2.3 on 2019-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_woman_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='kids_boy_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='kids_boy_image')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='kids_girl_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='kids_girl_image')),
                ('title', models.CharField(max_length=30)),
                ('price', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
