# Generated by Django 2.2.3 on 2019-08-25 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0007_auto_20190822_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('phone_number', models.IntegerField(default='')),
                ('product_code', models.CharField(default='', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_place', models.CharField(default='', max_length=30)),
                ('order_date', models.DateTimeField(default=datetime.datetime(2019, 8, 25, 23, 31, 53, 758996))),
                ('delivery_date', models.DateTimeField(default=datetime.datetime(2019, 8, 26, 23, 31, 53, 758996))),
            ],
            options={
                'verbose_name_plural': 'Order',
            },
        ),
    ]
