# Generated by Django 2.2.3 on 2019-08-26 11:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0010_auto_20190825_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 17, 37, 19, 874026)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 26, 17, 37, 19, 874026)),
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=200)),
                ('name', models.ForeignKey(default=None, on_delete='', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
